<?php

namespace SJ\ExampleBundle\Repository;

/**
 * EncryptionEntityTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncryptionEntityTestRepository extends \Doctrine\ORM\EntityRepository
{
}
