<?php

namespace SJ\ExampleBundle\Repository;

/**
 * EntityTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityTestRepository extends \Doctrine\ORM\EntityRepository
{
}
